upstreams:
  - name: Commons
    url: http://172.29.5.219:8080/commonsGraphQL
    priority: 0
  - name: Schools
    url: http://172.29.5.219:8081/schoolAffairsGraphQL
    priority: 1
  - name: Students
    url: http://172.29.5.219:8082/studentsGraphQL
    priority: 2
  - name: Ledgers
    url: http://172.29.5.219:8083/ledgersGraphQL
    priority: 3
  - name: Orchestrator
    url: http://172.29.5.219:8091/internalOrchestratorGraphQL
    priority: 4
